import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Provider from "./(Providers)/NextUiProviders";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });

const montserrat = Montserrat({ subsets: ["latin"], variable: '--font-monserrat' });

export const metadata: Metadata = {
  title: "PromptPalette | new universe of ia business",
  description: "Generated by omar",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserrat.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
